# Generated by Django 5.1.5 on 2025-06-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_visit_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(max_length=100, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='duration_days',
            field=models.IntegerField(verbose_name='Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Medication Name'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patient.visit', verbose_name='Visit'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_phone',
            field=models.CharField(max_length=15, verbose_name='Parent Phone'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patient.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='symptoms',
            field=models.TextField(verbose_name='Symptoms'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Visit Date'),
        ),
    ]
