# Generated by Django 5.1.5 on 2025-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_medication_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='name_af',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ast',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_bg',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_bs',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_cy',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_da',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_eo',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_et',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_fy',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ga',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_gd',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_hr',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_hu',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ia',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ig',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_io',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_is',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_kab',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_km',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_kn',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_lb',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_lt',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_lv',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ml',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_mn',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ms',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_my',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_nb',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_nn',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_os',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_pa',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_sk',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_te',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_tk',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_tt',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_udm',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ug',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ur',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='Medication Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_af',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ast',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_bg',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_bs',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_cy',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_da',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_eo',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_et',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_fy',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ga',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_gd',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_hr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_hu',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ia',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ig',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_io',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_is',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_kab',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_km',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_kn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_lb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_lt',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_lv',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ml',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_mn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ms',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_my',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_nb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_nn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_os',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_pa',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_sk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_te',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_tk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_tt',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_udm',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ug',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ur',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_af',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ar',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ar_dz',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ast',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_az',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_be',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_bg',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_bn',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_br',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_bs',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ca',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ckb',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_cs',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_cy',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_da',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_de',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_dsb',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_el',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_en',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_en_au',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_en_gb',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_eo',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_es',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_es_ar',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_es_co',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_es_mx',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_es_ni',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_es_ve',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_et',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_eu',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_fa',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_fi',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_fr',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_fy',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ga',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_gd',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_gl',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_he',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_hi',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_hr',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_hsb',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_hu',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_hy',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ia',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ig',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ind',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_io',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_is',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_it',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ja',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ka',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_kab',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_kk',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_km',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_kn',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ko',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ky',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_lb',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_lt',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_lv',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_mk',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ml',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_mn',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_mr',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ms',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_my',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_nb',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ne',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_nl',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_nn',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_os',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_pa',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_pl',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_pt',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_pt_br',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ro',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ru',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_sk',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_sl',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_sq',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_sr',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_sr_latn',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_sv',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_sw',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ta',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_te',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_tg',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_th',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_tk',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_tr',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_tt',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_udm',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ug',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_uk',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_ur',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_uz',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_vi',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_zh_hans',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_zh_hant',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_af',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ar_dz',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ast',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_az',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_be',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_br',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_bs',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ckb',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_cy',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_da',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_de',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_dsb',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_el',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_en_au',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_eo',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_es_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_es_co',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_es_mx',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_es_ni',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_es_ve',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_et',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_fy',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ga',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_gd',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_he',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_hr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_hsb',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_hu',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ig',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_io',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_is',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_it',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ka',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_kab',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_km',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_kn',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ko',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_lb',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_lt',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_lv',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_mk',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ml',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ms',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_my',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_nb',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ne',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_nn',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_os',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_pa',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_sk',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_sl',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_sq',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_sr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_sr_latn',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_te',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_tg',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_th',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_tk',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_tt',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_udm',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ug',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_ur',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_af',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ar',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ar_dz',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ast',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_az',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_be',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_bg',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_bn',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_br',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_bs',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ca',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ckb',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_cs',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_cy',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_da',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_de',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_dsb',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_el',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_en',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_en_au',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_en_gb',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_eo',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_es',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_es_ar',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_es_co',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_es_mx',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_es_ni',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_es_ve',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_et',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_eu',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_fa',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_fi',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_fr',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_fy',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ga',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_gd',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_gl',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_he',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_hi',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_hr',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_hsb',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_hu',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_hy',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ia',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ig',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ind',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_io',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_is',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_it',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ja',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ka',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_kab',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_kk',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_km',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_kn',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ko',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ky',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_lb',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_lt',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_lv',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_mk',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ml',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_mn',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_mr',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ms',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_my',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_nb',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ne',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_nl',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_nn',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_os',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_pa',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_pl',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_pt',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_pt_br',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ro',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ru',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_sk',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_sl',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_sq',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_sr',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_sr_latn',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_sv',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_sw',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ta',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_te',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_tg',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_th',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_tk',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_tr',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_tt',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_udm',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ug',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_uk',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_ur',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_uz',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_vi',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_zh_hans',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_zh_hant',
            field=models.TextField(null=True, verbose_name='Symptoms'),
        ),
    ]
