# Generated by Django 5.1.5 on 2025-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="E.g., 'en', 'fr', 'es'", max_length=5, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(help_text="E.g., 'English', 'French', 'Spanish'", max_length=100, verbose_name='Language Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active in Site')),
            ],
            options={
                'verbose_name': 'Site Language',
                'verbose_name_plural': 'Site Languages',
            },
        ),
    ]
