# Generated by Django 5.1.5 on 2025-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g., 'en', 'ar', 'fr'", max_length=5, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(max_length=100, verbose_name='Language Name')),
                ('is_active', models.BooleanField(default=True, help_text='Is this language available for users?', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.DeleteModel(
            name='SiteLanguage',
        ),
    ]
